dist: xenial
language: python
python:
- 3.4
- 3.5
- 3.6
- 3.7
script: echo "Dummpy Test"
jobs:
  include:
  - stage: deploy
    install: skip
    script:
    - openssl aes-256-cbc -K $encrypted_060c264bbabf_key -iv $encrypted_060c264bbabf_iv
      -in .travis/travis_key.enc -out ./travis_key -d
    - eval "$(ssh-agent -s)"
    - chmod 600 ./travis_key
    - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - ssh-add ./travis_key
    - ssh $SERVER_USERNAME@$SERVER_IP_ADDRESS bin/deploy_heartbeat.sh
before_install:

