"""empty message

Revision ID: 54200e1d49b0
Revises: b527827b7376
Create Date: 2019-10-05 08:04:54.286221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54200e1d49b0'
down_revision = 'b527827b7376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(length=128), nullable=False))
        batch_op.alter_column('pushover_key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               nullable=True)
        batch_op.alter_column('youtube_user_token',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               nullable=True)
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=False))
        batch_op.alter_column('youtube_user_token',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               nullable=False)
        batch_op.alter_column('pushover_key',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               nullable=False)
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
