"""empty message

Revision ID: b527827b7376
Revises: 
Create Date: 2019-08-19 01:40:28.484492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b527827b7376'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('initiator', sa.String(length=15), nullable=False),
    sa.Column('sent_datetime', sa.DateTime(), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('kwargs', sa.String(length=10000), nullable=False),
    sa.Column('response', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('pushover_key', sa.String(length=40), nullable=False),
    sa.Column('youtube_user_token', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('username', name=op.f('pk_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('notification')
    # ### end Alembic commands ###
